// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfiabfgpjkiyecfxkgfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmaWFiZmdwamtpeWVjZnhrZ2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjgyMzgsImV4cCI6MjA2MjgwNDIzOH0.WUJSL_boGe_KPNVpwP1EKhiTitDMuczMUL8se2pg15E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);